apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.labels.app }}
spec:
  containers:
  - name: "{{ .Values.appName }}-container"
    image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
    command: [
      'sh',
      '-c',
      'echo The app is running! && sleep 3600'
    ]
  initContainers:
  - name: init-container
    image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
    command: [
      'sh',
      '-c',
      'echo The init container is running... && sleep 120'
    ]