name: EKS-Cluster CI Test
on:
  push:
    branches:
      - '*'

jobs:
  validate:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run Tests
        run: make test